// model_generated.hpp
// Auto-generated by horndeski/codegen/cpp_emitter.py
// Model: NMDC (Einstein tensor non-minimal derivative coupling)
//
// DO NOT EDIT — regenerate by running cpp_emitter.py
//
// Conventions:
//   - Units: 8*pi*G = 1  (Mpl = 1 unless overridden)
//   - phi   = inflaton field value
//   - dphi  = d phi / dt  (cosmic time derivative)
//   - ddphi = d^2 phi / dt^2
//   - H     = Hubble parameter
//   - dH    = d H / dt
//   - X     = dphi^2 / 2  (kinetic term)
//
#pragma once
#include <cmath>

// ── Model parameters ─────────────────────────────────────────
static constexpr double Mpl = 1.0;
static constexpr double M = 1e-05;

// ── Potential: implement these in model.hpp or model.cpp ─────────
// double V_phi  (double phi);   // V(phi)
// double dV_phi (double phi);   // dV/dphi
//
// Or inline them here:

// ── Background ───────────────────────────────────────────────────
//
// Friedmann constraint:  3*H^2 = rho_phi(phi, dphi, H)
// Use this to solve for H given phi, dphi.

inline double rho_phi(double phi, double dphi, double H) {
    const double Mpl = 1.0;
    const double M = 1e-05;
    const double V_phi_val  = V_phi(phi);
    const double _t0 = pow(dphi, 2);
    return 9*pow(H, 2)*_t0/pow(M, 2) + V_phi_val + (1.0/2.0)*_t0;
}

inline double dH_rhs(double phi, double dphi, double H, double ddphi) {
    const double Mpl = 1.0;
    const double M = 1e-05;
    const double _t0 = pow(dphi, 2);
    const double _t1 = pow(M, 2);
    return -_t0*(3*pow(H, 2) + (1.0/2.0)*_t1)/(pow(Mpl, 2)*_t1 - 3*_t0 + _t1);
}

inline double ddphi_rhs(double phi, double dphi, double H, double dH) {
    const double Mpl = 1.0;
    const double M = 1e-05;
    const double dV_phi_val = dV_phi(phi);
    const double _t0 = pow(M, 2);
    const double _t1 = H*dphi;
    return -(_t0*(3*_t1 + dV_phi_val) + 6*_t1*dH)/(6*pow(H, 2) + _t0);
}

inline double epsilon_H(double phi, double dphi, double H) {
    const double Mpl = 1.0;
    const double M = 1e-05;
    const double _t0 = pow(H, 2);
    const double _t1 = pow(dphi, 2);
    const double _t2 = pow(M, 2);
    return (1.0/2.0)*_t1*(6*_t0 + _t2)/(_t0*(pow(Mpl, 2)*_t2 - 3*_t1 + _t2));
}

// ── Perturbations ────────────────────────────────────────────────
//
// Stability conditions:
//   QT  > 0   (no tensor ghost)
//   Qs  > 0   (no scalar ghost)
//   cT2 > 0   (no tensor gradient instability)
//   cs2 > 0   (no scalar gradient instability)

inline double QT(double phi, double dphi, double H) {
    const double Mpl = 1.0;
    const double M = 1e-05;
    return pow(Mpl, 2) + pow(dphi, 2)/pow(M, 2);
}

inline double cT2(double phi, double dphi, double H) {
    const double Mpl = 1.0;
    const double M = 1e-05;
    const double _t0 = pow(dphi, 2);
    const double _t1 = pow(M, 2)*pow(Mpl, 2);
    return (-_t0 + _t1)/(_t0 + _t1);
}

inline double Qs(double phi, double dphi, double H) {
    const double Mpl = 1.0;
    const double M = 1e-05;
    const double _t0 = pow(H, 2);
    const double _t1 = pow(M, 2);
    const double _t2 = pow(dphi, 2);
    const double _t3 = pow(Mpl, 2)*_t1;
    const double _t4 = -_t2;
    return (3.0/2.0)*_t2*(6*_t0 + _t1)*pow(_t2 + _t3, 2)/(_t0*_t1*(_t3 + _t4)*(3*_t3 + _t4));
}

inline double cs2(double phi, double dphi, double H, double dH, double ddphi) {
    const double Mpl = 1.0;
    const double M = 1e-05;
    const double _t0 = 6*pow(H, 2) + pow(M, 2);
    return -(4*H*ddphi - _t0*dphi + 4*dH*dphi)/(_t0*dphi);
}

// ── Mukhanov-Sasaki pump fields ───────────────────────────────────
//
// z^2 = a^2 * 2*Qs  ->  used in scalar MS equation
// u^2 = a^2 * QT/2  ->  used in tensor MS equation
//
// z''/z and u''/u are computed numerically in perturbations.cpp
// using finite differences on the background trajectory.

inline double z2_over_a2(double phi, double dphi, double H) {
    return 2.0 * Qs(phi, dphi, H);
}

inline double u2_over_a2(double phi, double dphi, double H) {
    return 0.5 * QT(phi, dphi, H);
}
