// model_generated.hpp
// Auto-generated by horndeski/codegen/cpp_emitter.py
// Model: user model
//
// DO NOT EDIT — regenerate by running cpp_emitter.py
//
// Conventions:
//   - Units: 8*pi*G = 1  (Mpl = 1 unless overridden)
//   - phi   = inflaton field value
//   - dphi  = d phi / dt  (cosmic time derivative)
//   - ddphi = d^2 phi / dt^2
//   - H     = Hubble parameter
//   - dH    = d H / dt
//   - X     = dphi^2 / 2  (kinetic term)
//
#pragma once
#include <cmath>

// ── Model parameters ─────────────────────────────────────────
static constexpr double Mpl = 1.0;
static constexpr double M = 0.001;

// ── Potential: implement these in model.hpp or model.cpp ─────────
// double V_phi  (double phi);   // V(phi)
// double dV_phi (double phi);   // dV/dphi
//
// Or inline them here:

// ── Background ───────────────────────────────────────────────────
//
// Friedmann constraint:  3*H^2 = rho_phi(phi, dphi, H)
// Use this to solve for H given phi, dphi.

inline double rho_phi(double phi, double dphi, double H) {
    const double Mpl = 1.0;
    const double M = 0.001;
    const double V_phi_val  = V_phi(phi);
    return V_phi_val + (1.0/2.0)*pow(dphi, 2);
}

inline double dH_rhs(double phi, double dphi, double H) {
    const double Mpl = 1.0;
    const double M = 0.001;
    return -1.0/2.0*pow(dphi, 2)/pow(Mpl, 2);
}

inline double ddphi_rhs(double phi, double dphi, double H) {
    const double Mpl = 1.0;
    const double M = 0.001;
    const double dV_phi_val = dV_phi(phi);
    return -3*H*dphi - dV_phi_val;
}

inline double epsilon_H(double phi, double dphi, double H) {
    const double Mpl = 1.0;
    const double M = 0.001;
    return (1.0/2.0)*pow(dphi, 2)/(pow(H, 2)*pow(Mpl, 2));
}

// ── Perturbations ────────────────────────────────────────────────
//
// Stability conditions:
//   QT  > 0   (no tensor ghost)
//   Qs  > 0   (no scalar ghost)
//   cT2 > 0   (no tensor gradient instability)
//   cs2 > 0   (no scalar gradient instability)

inline double QT(double phi, double dphi, double H) {
    const double Mpl = 1.0;
    const double M = 0.001;
    return pow(Mpl, 2);
}

inline double cT2(double phi, double dphi, double H) {
    const double Mpl = 1.0;
    const double M = 0.001;
    return 1;
}

inline double Qs(double phi, double dphi, double H) {
    const double Mpl = 1.0;
    const double M = 0.001;
    return (1.0/2.0)*pow(dphi, 2)/pow(H, 2);
}

inline double cs2(double phi, double dphi, double H, double dH, double ddphi) {
    const double Mpl = 1.0;
    const double M = 0.001;
    return -2*pow(Mpl, 2)*dH/pow(dphi, 2);
}

// ── Mukhanov-Sasaki pump fields ───────────────────────────────────
//
// z^2 = a^2 * 2*Qs  ->  used in scalar MS equation
// u^2 = a^2 * QT/2  ->  used in tensor MS equation
//
// z''/z and u''/u are computed numerically in perturbations.cpp
// using finite differences on the background trajectory.

inline double z2_over_a2(double phi, double dphi, double H) {
    return 2.0 * Qs(phi, dphi, H);
}

inline double u2_over_a2(double phi, double dphi, double H) {
    return 0.5 * QT(phi, dphi, H);
}
